// Copies the vault/venue ABIs from Foundry's build output and the deployment address books
// into src/generated so the app always matches the contracts in this repo.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const outDir = join(root, "frontend", "src", "generated");
mkdirSync(outDir, { recursive: true });

const abi = (name) => JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8")).abi;

const deployments = {};
for (const f of readdirSync(join(root, "deployments"))) {
  const m = f.match(/^(\d+)\.json$/);
  if (m) deployments[m[1]] = JSON.parse(readFileSync(join(root, "deployments", f), "utf8"));
}

writeFileSync(
  join(outDir, "contracts.ts"),
  `// Generated by scripts/export-abi.mjs. Do not edit.
export const vaultAbi = ${JSON.stringify(abi("WhisperVault"))} as const;
export const venueAbi = ${JSON.stringify(abi("OracleVenue"))} as const;
export const deployments: Record<string, { vault: \`0x\${string}\`; venue: \`0x\${string}\`; operator: \`0x\${string}\` }> = ${JSON.stringify(deployments, null, 2)};
`,
);
console.log(`abi exported; deployments for chains: ${Object.keys(deployments).join(", ") || "none"}`);
